# Generated by Django 5.0.4 on 2024-05-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='usuario',
            new_name='nome',
        ),
    ]
