# Generated by Django 5.0.4 on 2024-05-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nutricao', 'Nutrição'), ('treino', 'Treino'), ('cardio', 'Cardio')], max_length=20)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='aluno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=100),
        ),
    ]
