# Generated by Django 5.0.4 on 2024-05-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nutricao', 'Nutrição'), ('treino', 'Treino'), ('cardio', 'Cardio')], max_length=20)),
                ('texto', models.TextField()),
            ],
        ),
    ]
