# Generated by Django 5.0.4 on 2024-05-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_treinopredefinido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.dados'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
