# Generated by Django 5.0.4 on 2024-05-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_feedback_aluno_alter_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progresso',
        ),
    ]
