# Generated by Django 5.0.4 on 2024-05-16 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_delete_progresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressoaluno',
            name='nome_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.dados'),
        ),
    ]
