# Generated by Django 5.0.4 on 2024-05-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_progressoaluno_nome_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressoaluno',
            name='metrica',
            field=models.CharField(choices=[('peso', 'Peso'), ('repeticoes', 'Repetições'), ('tempo', 'Tempo'), ('circunferencia', 'Circunferência'), ('porcentagem_de_gordura', 'Porcentagem de Gordura'), ('niveis_de_energia', 'Níveis de Energia')], max_length=100),
        ),
    ]
