# Generated by Django 5.0.4 on 2024-05-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_duvida_nome_treinador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_treino', models.CharField(choices=[('costas', 'Costas'), ('peito', 'Peito'), ('perna', 'Perna'), ('braco', 'Braço')], max_length=100)),
                ('exercicio1', models.CharField(max_length=100)),
                ('series1', models.PositiveIntegerField()),
                ('repeticoes1', models.PositiveIntegerField()),
                ('exercicio2', models.CharField(max_length=100)),
                ('series2', models.PositiveIntegerField()),
                ('repeticoes2', models.PositiveIntegerField()),
                ('exercicio3', models.CharField(max_length=100)),
                ('series3', models.PositiveIntegerField()),
                ('repeticoes3', models.PositiveIntegerField()),
                ('exercicio4', models.CharField(max_length=100)),
                ('series4', models.PositiveIntegerField()),
                ('repeticoes4', models.PositiveIntegerField()),
                ('nome_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.dados')),
            ],
        ),
    ]
