# Generated by Django 5.0.4 on 2024-05-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_treino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treino',
            old_name='exercicio1',
            new_name='exercicio1_nome',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='repeticoes1',
            new_name='exercicio1_repeticoes',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='repeticoes2',
            new_name='exercicio1_series',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='exercicio2',
            new_name='exercicio2_nome',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='repeticoes3',
            new_name='exercicio2_repeticoes',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='repeticoes4',
            new_name='exercicio2_series',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='exercicio3',
            new_name='exercicio3_nome',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='series1',
            new_name='exercicio3_repeticoes',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='series2',
            new_name='exercicio3_series',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='exercicio4',
            new_name='exercicio4_nome',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='series3',
            new_name='exercicio4_repeticoes',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='series4',
            new_name='exercicio4_series',
        ),
    ]
