# Generated by Django 5.0.4 on 2024-05-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_rename_nome_aluno_treino_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treino',
            old_name='aluno',
            new_name='nome_aluno',
        ),
    ]
