# Generated by Django 5.0.4 on 2024-05-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_rename_aluno_treino_nome_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treino',
            old_name='nome_aluno',
            new_name='aluno',
        ),
    ]
