# Generated by Django 5.0.4 on 2024-05-27 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_rename_nome_aluno_treino_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_meta', models.CharField(choices=[('perda de peso', 'Perda de Peso'), ('ganho de massa', 'Ganho de Massa'), ('melhoria de resistencia', 'Melhoria de Resistência')], max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.dados')),
            ],
        ),
    ]
