# Generated by Django 5.0.4 on 2024-05-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_alter_info_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
